server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 60 * 60 * 12  # 12시간
  refresh-token-validity: 60 * 60 * 24  # 24시간

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
  file:
    name: logs/auth-service/application.log