server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: notification-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host:  ${REDIS_HOST}
      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  message:
    kafka:
      host: ${KAFKA_HOST}
      post: ${KAFKA_PORT}
      group-id: ${KAFKA_GROUP}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
  file:
    name: /var/log/applications/${spring.application.name}/application.log