server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: image-service
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ${AWS_REGION}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
  file:
    name: /var/log/applications/${spring.application.name}/application.log