server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: awss3
  cloud:
    config:
      server:
        awss3:
          region: ${AWS_REGION}
          bucket: ${AWS_BUCKET_NAME}
    bus:
      enabled: true
      refresh:
        enabled: true
      kafka:
        bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,busrefresh
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.aws: DEBUG
    com.amazonaws: DEBUG
  file:
    name: logs/config-service/application.log