server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push 

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: auth-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth-service
          __path__: /logs/auth-service/*.log  

  - job_name: chat-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: chat-service
          __path__: /logs/chat-service/*.log 

  - job_name: gateway-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: gateway-service
          __path__: /logs/gateway-service/*.log 

  - job_name: health-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: health-service
          __path__: /logs/health-service/*.log 

  - job_name: log-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: log-service
          __path__: /logs/log-service/*.log 

  - job_name: notification-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: notification-service
          __path__: /logs/notification-service/*.log 

  - job_name: user-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          __path__: /logs/user-service/*.log 
