server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: context-service
  data:
    mongodb:
      uri: mongodb://${CONTEXT_DB_USERNAME:contextuser}:${CONTEXT_DB_PASSWORD:contextpass}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27018}/${CONTEXT_DB_NAME:contextdb}?authSource=contextdb
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6383}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  jackson:
    time-zone: Asia/Seoul

kakao:
  api:
    url: ${KAKAO_API_URL}
    key: ${KAKAO_API_KEY}

health:
  threshold:
    max-heart-rate: 180
    min-heart-rate: 40
    normal-stress-level: 13
    mild-stress-level: 16
    moderate-stress-level: 18
    severe-stress-level: 19
    min-sleep-minutes: 180
    max-sleep-minutes: 600

resilience4j:
  circuitbreaker:
    instances:
      weatherApi:
        slidingWindowSize: 10 # 10개의 요청을 기준으로 실패율 계산
        minimumNumberOfCalls: 5 # 최소 5개 요청이 있어야 실패율 계산
        waitDurationInOpenState: 30s # Circuit 이 Open 상태일 때 30초 대기
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      weatherApi:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
  file:
    name: /var/log/applications/${spring.application.name}/application.log

weather:
  api:
    key: ${WEATHER_API_KEY}
    url: ${WEATHER_API_URL}
  fetch:
    cron: ${WEATHER_FETCH_CRON}